### ISSUE TITLE
ローカル開発環境でログインが出来ない

### ISSUE THREAD

**Issue by underground0930** [dokugaku-engineer/dokugaku-engineer#95]
@kiyodori
お手数ですが、
お時間ある時にご教授いただけると幸いです。

# 背景

READMEを元に環境構築を行い, dockerを動かしてみたのですが
トップからログイン出来ずに /course/serverside ページに遷移出来ない。

### ソーシャルログイン githubを試す

top → auth0ログイン画面 → continue with githubを選択 → githubの id, passを入力する → TOPページにリダイレクトしてしまう

### ソーシャルログイン twitterを試す

アプリの申請をしないとダメそうなので、断念

### メールアドレスとパスワードのアカウントでログインしようと試す

ログイン出来ず
<img width="406" alt="スクリーンショット 2021-09-27 15 23 56" src="https://user-images.githubusercontent.com/4293172/134855124-d3ef1ccc-a52c-4391-95e9-7200797eda53.png">

## やりたいこと

ログインが出来る方法を知りたい。
（開発用のログインアカウントが必要？）

**Comment by kiyodori** [comment]
READMEの「ユーザー認証の設定」の箇所を御覧ください。
https://github.com/dokugaku-engineer/dokugaku-engineer#%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E8%AA%8D%E8%A8%BC%E3%81%AE%E8%A8%AD%E5%AE%9A
