### ISSUE TITLE
レッスンの詳細ページの動画下のpagerボタンをPCでも出して欲しい

### ISSUE THREAD

**Issue by underground0930** [dokugaku-engineer/dokugaku-engineer#98]
@kiyodori 

# 背景

レッスンの詳細ページの動画下のpagerボタンがPCでは出ないので前後レッスンへの移動が不便
https://github.com/dokugaku-engineer/dokugaku-engineer/blob/master/client/pages/course/_name/lecture/_slug/index.vue#L79-L94

## やりたいこと

PCでもpagerボタンを出して欲しい

**Comment by kiyodori** [comment]
PCでは動画にマウスホバーすると前後の動画へ遷移する矢印ボタンが表示されるようにしております。そのためこちらはクローズドいたしますね。

<img width="1362" alt="スクリーンショット 2022-02-18 6 10 25" src="https://user-images.githubusercontent.com/3000667/154571400-a39a6a64-1dd2-4504-b9cd-e0e5bb78fba0.png">
